name: Update badges

on:
  # run automatically every day
  schedule:
    - cron: "0 2 * * *"     # Runs at 2am UTC
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master
    
jobs:
  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'
          persist-credentials: false
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: bryan-li712
          BADGE_SIZE: 180
          NUMBER_LAST_BADGES: 28
      - name: Commit and push changes
        run: |
          git config user.name Zy8712
          git config user.email ${{ secrets.MY_README_EMAIL_VALUE }}
          git add README.md
          git commit -m "Update badges"
          git push -f origin master
        env:
          GITHUB_TOKEN: ${{ secrets.BADGES_PAT }}
