name: Update badges

on:
  workflow_dispatch: # run manually
jobs:
  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: bryan-li712
          BADGE_SIZE: 180
          NUMBER_LAST_BADGES: 28
