name: Update badges

on:
  # run automatically every day (commented out due to issues, manual push when update needed)
  #schedule:
    - #cron: "0 2 * * *"     # Runs at 2am UTC
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
jobs:
  update-badges:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: bryan-li712
          BADGE_SIZE: 110
          NUMBER_LAST_BADGES: 24
